spring:
  application:
    name: gulimall-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      routes:
        - id: test_route
          uri: https://www.baidu.com
          predicates:
            - Path=/test

        - id: test_ww
          uri: https://www.qq.com
          predicates:
            - Query=url,qq

        # 配置路由至gulimall-product服务
        - id: product_route
          uri: lb://gulimall-product
          predicates:
            - Path=/api/product/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

server:
  port: 88
logging:
    level:
      root: debug   # 设置当前区域日志打印级别为debug
